---
title: "Bio Project"
output: html_document
date: '2022-04-09'
---

```{r libraries}
require(readxl)
require(dplyr)
require(ggplot2)
require(tidyverse)
require(spaMM)
require(DHARMa)
set.seed(452)
```

```{r read-data}
bur <- read_excel("BUR ONLY DATA FOR SPATIAL ANALYSIS (GROWTH).xlsx")
```

# Initial Investigations

```{r plot-1}
bur %>%
    ggplot(aes(x = X, y = Y, color = DBH95)) + 
    geom_point() + 
    theme_classic()
```

```{r plot-2}
bur %>% 
  ggplot(aes(x = GROWTH)) +
  geom_density()
```

```{r plot-3}
bur %>% 
  ggplot(aes(x = GROWTH)) +
  geom_dotplot()
```

```{r}
# Removed 1 extreme outlier
bur2 <- bur %>% 
  filter(GROWTH > -40)
```

```{r plot-4}
bur2 %>% 
  ggplot(aes(x = GROWTH)) +
  geom_density()
```

```{r}
model <- fitme(GROWTH ~ ELEVA + DBH95 + Matern(1 | X + Y), data = bur2, fixed = list(nu = 0.5))

summary(model)
```

```{r}
model2 <- fitme(GROWTH ~ ELEVA + DBH95 + Matern(1 | X + Y), data = bur2, family = "gaussian")

summary(model2)
```


```{r}
model.map <- cbind(bur2, spamm_pred = predict(model)) %>%
    mutate(spamm_resid = GROWTH - spamm_pred)

model.map2 <- cbind(bur2, spamm_pred2 = predict(model2)) %>%
    mutate(spamm_resid2 = GROWTH - spamm_pred2)
```

```{r}
model.map %>% 
  ggplot(aes(x = X, y = Y, color = spamm_resid)) +
  geom_point() + 
  theme_classic() +
  scale_color_gradient2(low = "blue", mid = "lightgrey", high = "red")

model.map2 %>% 
  ggplot(aes(x = X, y = Y, color = spamm_resid2)) +
  geom_point() + 
  theme_classic() +
  scale_color_gradient2(low = "blue", mid = "lightgrey", high = "red")
```

```{r}
## Compare RMSE
sqrt(mean(model.map$spamm_resid^2))

sqrt(mean(model.map2$spamm_resid2^2))
```

```{r}
simulation <- simulateResiduals(model2)

plotQQunif(simulation)

plotResiduals(simulation, form = bur2$ELEVA)

plotResiduals(simulation, form = bur2$DBH95)
```

```{r}
# Extreme Residuals (higher or lower than what we'd expect)
model.map2 %>%
    filter(abs(scale(spamm_resid2)) > 3)
```




