---
title: "Tree survival modeling"
author: "Erin Franke"
date: "4/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data and libraries
```{r}
library(readxl)
library(tidyverse)
library(spaMM)
library(RSpectra)
library(ROI.plugin.glpk)
library(raster)
library(ggtext)
bur_survival <- read_xlsx("BUR ONLY DATA FOR SPATIAL ANALYSIS (SURVIVAL).xlsx") %>%
  mutate(survived = case_when(`Y20 D/L` == "D"~ 0, 
                              TRUE ~ 1))
pin_survival <- read_xlsx("PIN ONLY DATA FOR SPATIAL ANALYSIS (SURVIVAL).xlsx") %>%
  mutate(survived = case_when(`Y20 D/L` == "D"~ 0, 
                              TRUE ~ 1))

pin_survival <- pin_survival %>%
  as.data.frame() 
```

Exploratory Data analysis for relationship between `DBH95`, `ELEVA` and `LOG(N)` with tree survival for PIN trees.
```{r}
pin_survival %>%
  mutate(ELEVACat = cut(ELEVA,20)) %>%
  group_by(ELEVACat) %>% 
  summarize(prop = mean(survived,na.rm=TRUE)) %>%
  ggplot(aes(x = ELEVACat, y = prop)) + 
  geom_point()+
  theme_classic()+
  labs(title = "Survival rate for Pin trees by elevation category", y="", x="")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono"), 
        axis.text.x = element_text(family = "mono", angle = 90), 
        axis.text.y = element_text(family= "mono"))

pin_survival %>%
  mutate(Cat = cut(`LOG(N)`,10)) %>%
  group_by(Cat) %>% 
  summarize(prop = mean(survived,na.rm=TRUE)) %>%
  ggplot(aes(x = Cat, y = prop)) + 
  geom_point()+
  theme_classic()+
  labs(title = "Survival rate for Pin trees by LOG(N) category", y="", x="")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono"), 
        axis.text.x = element_text(family = "mono", angle = 90), 
        axis.text.y = element_text(family= "mono"))

pin_survival %>%
  mutate(Cat_DBH = cut(DBH95,10)) %>%
  group_by(Cat_DBH) %>% 
  summarize(prop = mean(survived,na.rm=TRUE)) %>%
  ggplot(aes(x = Cat_DBH, y = prop)) + 
  geom_point()+
  theme_classic()+
  labs(title = "Survival rate for Pin trees by diameter", y="", x="")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono"), 
        axis.text.x = element_text(family = "mono", angle = 90), 
        axis.text.y = element_text(family= "mono"))

pin_survival %>% 
    ggplot(aes(X, Y)) + 
  geom_density2d(color = "black", lwd = 0.2) +
    geom_point(aes(color = as.factor(survived)), alpha = 0.3)+
  scale_color_manual(values = c("darkred", "darkgreen"))+
    theme_classic()+
  labs(title = "Pin trees tend to <strong><span style='color:darkred'>die</span></strong></b> more frequently at higher elevations and <strong><span style='color:darkgreen'>survive</span></strong></b> at lower ones")+
  theme(legend.position = "none",
        plot.title.position = "plot", 
        plot.title = element_markdown(family = "mono", size = 8), 
        axis.text = element_text(family = "mono"), 
        axis.title = element_text(family = "mono"))
```

Exploratory Data analysis for relationship between `DBH95`, `ELEVA` and `LOG(N)` with tree survival for BUR trees.
```{r}
bur_survival %>%
  mutate(ELEVACat = cut(ELEVA,20)) %>%
  group_by(ELEVACat) %>% 
  summarize(prop = mean(survived,na.rm=TRUE)) %>%
  ggplot(aes(x = ELEVACat, y = prop)) + 
  geom_point()+
  theme_classic()+
  labs(title = "Survival rate for Bur trees by elevation category", y="", x="")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono"), 
        axis.text.x = element_text(family = "mono", angle = 90), 
        axis.text.y = element_text(family= "mono"))

bur_survival %>%
  mutate(Cat = cut(`LOG(N)`,10)) %>%
  group_by(Cat) %>% 
  summarize(prop = mean(survived,na.rm=TRUE)) %>%
  ggplot(aes(x = Cat, y = prop)) + 
  geom_point()+
  theme_classic()+
  labs(title = "Survival rate for Bur trees by LOG(N) category", y="", x="")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono"), 
        axis.text.x = element_text(family = "mono", angle = 90), 
        axis.text.y = element_text(family= "mono"))

bur_survival %>%
  mutate(Cat_DBH = cut(DBH95,10)) %>%
  group_by(Cat_DBH) %>% 
  summarize(prop = mean(survived,na.rm=TRUE)) %>%
  ggplot(aes(x = Cat_DBH, y = prop)) + 
  geom_point()+
  theme_classic()+
  labs(title = "Survival rate for Bur trees by diameter", y="", x="")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono"), 
        axis.text.x = element_text(family = "mono", angle = 90), 
        axis.text.y = element_text(family= "mono"))

bur_survival %>% 
    ggplot(aes(X, Y)) + 
  geom_density2d(color = "black", lwd = 0.2) +
    geom_point(aes(color = as.factor(survived)), alpha = 0.3)+
  scale_color_manual(values = c("darkred", "darkgreen"))+
    theme_classic()+
  labs(title = "Bur tree <strong><span style='color:darkred'>death</span></strong></b> and <strong><span style='color:darkgreen'>survival</span></strong></b> patterns by elevation are not as clear as pin trees")+
  theme(legend.position = "none",
        plot.title.position = "plot", 
        plot.title = element_markdown(family = "mono", size = 8), 
        axis.text = element_text(family = "mono"), 
        axis.title = element_text(family = "mono"))
```

PIN modeling
```{r}
pin_survival$region <- paste0('X',cut(pin_survival$X,breaks=seq(20,420,length = 10)),'Y',cut(pin_survival$Y,breaks=seq(0,400,length = 10)))

pin_survival %>%
  #mutate(ELEVACat = cut(ELEVA,3)) %>%
  arrange(region) %>%
geeM::geem(survived ~ ELEVA + DBH95, family = binomial(),id = region, data = .,corstr='exchangeable') %>% summary()

pin_survival %>%
  #mutate(ELEVACat = cut(ELEVA,3)) %>%
  arrange(region) %>%
geeM::geem(survived ~ `LOG(N)` + DBH95, family = binomial(),id = region, data = .,corstr='exchangeable') %>% summary()


```

```{r}
#pin_mod1 <- fitme(survived ~ cut(ELEVA,3) + DBH95 + Matern(1 | X+Y), fixed = list(nu = 0.5), family = binomial(), data=pin_survival,control.HLfit = list(algebra='decorr'))



#library(glmmTMB)
# fitst we need to create a numeric factor recording the coordinates of the sampled locations
#pin_survival$pos <- numFactor(scale(pin_survival$X), scale(pin_survival$Y))
# then create a dummy group factor to be used as a random term
#pin_survival$ID <- factor(rep(1, nrow(pin_survival)))

# fit the model
#m_tmb <- glmmTMB(survived ~ cut(ELEVA,3) + DBH95 + mat(pos + 0 | ID), pin_survival, family = binomial()) # take some time to fit
# model summary of fixed effects
#summary(m_tmb)
```


